In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Chapter 4 - Example - Data.csv', header=None)
data1=np.array([data]).reshape(-1,1)

In [3]:
unique, count = np.unique(data, return_counts=True)

In [4]:
hist,bin_edge=np.histogram(data,bins=np.arange(256),density=True)

In [5]:

lk=hist.cumsum()
lk

array([0.00585938, 0.00683594, 0.00683594, 0.00683594, 0.00683594,
       0.00683594, 0.00683594, 0.00878906, 0.00878906, 0.01074219,
       0.01269531, 0.01464844, 0.01855469, 0.01953125, 0.02148438,
       0.02539062, 0.02539062, 0.02929688, 0.03222656, 0.03710938,
       0.04003906, 0.04394531, 0.046875  , 0.05078125, 0.05664062,
       0.06152344, 0.06835938, 0.07421875, 0.07910156, 0.08789062,
       0.09472656, 0.09863281, 0.10351562, 0.10449219, 0.11035156,
       0.11914062, 0.12890625, 0.13867188, 0.14648438, 0.15332031,
       0.16015625, 0.171875  , 0.17773438, 0.18652344, 0.19335938,
       0.20507812, 0.21191406, 0.22558594, 0.23242188, 0.24609375,
       0.26171875, 0.26855469, 0.28222656, 0.2890625 , 0.29882812,
       0.30566406, 0.31738281, 0.33496094, 0.34082031, 0.34570312,
       0.35742188, 0.36816406, 0.37109375, 0.37890625, 0.38574219,
       0.39453125, 0.40429688, 0.41113281, 0.41699219, 0.421875  ,
       0.42773438, 0.43359375, 0.43847656, 0.45019531, 0.46093

In [6]:
bin_edge

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
uT=sum(np.multiply(np.arange(255),hist))
ut=np.multiply(np.arange(255),hist)
ut=ut.cumsum()

In [8]:
ut.shape

(255,)

In [12]:
a=np.subtract(lk*uT,ut)
a=a**2
b=lk*(1-lk)

In [13]:
a/b

C:\Users\PhuTuan\AppData\Local\Temp\ipykernel_15944\1348051284.py:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([  61.11492687,   71.17074349,   71.17074349,   71.17074349,
         71.17074349,   71.17074349,   71.17074349,   88.95824658,
         88.95824658,  106.06032031,  122.86978159,  139.38367061,
        171.90095199,  179.89103872,  195.5531442 ,  226.3614456 ,
        226.3614456 ,  255.98482472,  277.84510073,  313.72511017,
        334.91863557,  362.69399162,  383.16358777,  409.97418735,
        449.61882012,  482.21811205,  527.29554381,  565.49576118,
        596.88186131,  652.78160043,  695.90175258,  720.18024549,
        749.99876802,  755.83338324,  790.11435297,  841.00263111,
        897.25470293,  953.28703506,  997.81329904, 1036.35159056,
       1074.41454054, 1139.30881825, 1171.53315627, 1219.33067054,
       1256.1421482 , 1318.90469285, 1355.31962946, 1427.98637862,
       1464.24453351, 1536.62823668, 1620.39692573, 1657.12214226,
       1730.52273942, 1767.20910771, 1819.2703786 , 1855.47546967,
       1917.35894115, 2011.74264934, 2043.42243849, 2069.40701

In [10]:
c=a[:253]/b[:253]
t=np.unravel_index(np.argmax(c,axis=0),c.shape[0])

In [11]:
print(f"Nguong cat max: {t[0]}")

Nguong cat max: 114
